'use strict';
// Browser-only development check; never loaded by the offline site.
const assert = require('node:assert/strict');
const fs = require('node:fs');
const { chromium } = require('playwright');
const { spawn } = require('node:child_process');
const base = 'http://127.0.0.1:8766';
(async () => {
  const server = spawn('python3', ['-m', 'http.server', '8766', '--bind', '127.0.0.1']);
  let browser;
  try {
    for (let i = 0; i < 40; i++) {
      try { if ((await fetch(base)).ok) break; } catch (_) {}
      await new Promise(resolve => setTimeout(resolve, 100));
    }
    browser = await chromium.launch(process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE ? { executablePath: process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE } : {});
    fs.mkdirSync('test-results', { recursive: true });
    for (const viewport of [{ width: 1440, height: 1000 }, { width: 390, height: 844 }]) {
      const page = await browser.newPage({ viewport });
      const errors = [];
      page.on('pageerror', error => errors.push(error.message));
      page.on('response', response => { if (response.status() >= 400) errors.push(`${response.status()} ${response.url()}`); });
      await page.goto(`${base}/#/lab/covariance`);
      await page.locator('#cov-next').waitFor();
      assert.equal(await page.locator('#cov-step-count').textContent(), '1 / 5');
      assert.equal(await page.locator('#cov-prev').isDisabled(), true);
      assert.equal(await page.locator('#cov-after').isVisible(), false);
      assert.equal(await page.locator('.cov-table thead th').count(), 3);
      for (let step = 2; step <= 5; step++) {
        await page.locator('#cov-next').click();
        assert.equal(await page.locator('#cov-step-count').textContent(), `${step} / 5`);
        assert.equal(await page.locator('.cov-table thead th').count(), step < 3 ? 3 : step === 3 ? 5 : 6);
      }
      assert.equal(await page.locator('#cov-next').isDisabled(), true);
      assert.match(await page.locator('#cov-result-value').textContent(), /\+166\.6667/);
      assert.equal(await page.locator('.cov-feedback:visible').count(), 0);
      await page.locator('#cov-basis').selectOption('sample');
      assert.match(await page.locator('#cov-result-value').textContent(), /\+250/);
      await page.locator('[data-question="0"][data-answer="0"]').click();
      assert.match(await page.locator('#cov-feedback-0').textContent(), /再想一想/);
      await page.locator('[data-question="0"][data-answer="1"]').click();
      assert.match(await page.locator('#cov-feedback-0').textContent(), /答对了/);
      assert.equal(await page.locator('[data-question="0"][aria-pressed="true"]').count(), 1);
      await page.locator('#cov-case').selectOption('opposite');
      assert.equal(await page.locator('#cov-step-count').textContent(), '1 / 5');
      await page.locator('[data-step="5"]').click();
      assert.equal(await page.locator('.cov-feedback:visible').count(), 0);
      assert.equal(await page.locator('#cov-basis').inputValue(), 'population');
      assert.match(await page.locator('#cov-result-value').textContent(), /-166\.6667/);
      await page.locator('#cov-basis').selectOption('sample');
      assert.match(await page.locator('#cov-result-value').textContent(), /-250/);
      await page.locator('[data-day="3"]').click();
      assert.match(await page.locator('#cov-detail').textContent(), /第 3 天.*反向偏离/);
      assert.equal(await page.evaluate(() => document.activeElement.dataset.day), '3');
      await page.evaluate(() => window.scrollTo({ top: 0, behavior: 'instant' }));
      await page.screenshot({ path: `test-results/covariance-${viewport.width}.png`, fullPage: true });
      assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1), true, 'page-wide horizontal overflow');
      await page.locator('#cov-case').selectOption('zero');
      await page.locator('[data-step="5"]').click();
      assert.match(await page.locator('#cov-result-value').textContent(), /^0 /);
      assert.match(await page.locator('#cov-summary').textContent(), /非线性关系/);
      await page.locator('#cov-reset').click();
      assert.equal(await page.locator('#cov-step-count').textContent(), '1 / 5');
      assert.equal(await page.locator('#cov-after').isVisible(), false);
      // Keyboard control and theme changes must not reset or duplicate listeners.
      await page.locator('[data-step="4"]').focus();
      await page.keyboard.press('Enter');
      assert.equal(await page.locator('#cov-step-count').textContent(), '4 / 5');
      await page.locator('#theme-toggle').click();
      assert.equal(await page.locator('#cov-step-count').textContent(), '4 / 5');
      await page.evaluate(() => window.scrollTo({ top: 0, behavior: 'instant' }));
      await page.screenshot({ path: `test-results/covariance-dark-${viewport.width}.png`, fullPage: true });
      await page.goto(`${base}/#/lesson/l04`);
      await page.locator('#article-body').waitFor();
      assert.equal(await page.locator('#article-body details[open]').count(), 0);
      assert.ok(await page.locator('#article-body a[href="#/lab/covariance"]').count() >= 1);
      // Embedded correlation lessons: image bytes, unit scaling, portfolios, hidden answers and repeated changes.
      await page.locator('#cor-unit').waitFor();
      for (const image of await page.locator('.cor-figure img').all()) {
        await image.scrollIntoViewIfNeeded();
        await image.evaluate(async img => { if (!img.complete) await new Promise((resolve, reject) => { img.onload = resolve; img.onerror = reject; }); if (!img.naturalWidth) throw new Error('image missing'); });
      }
      assert.match(await page.locator('#cor-unit-result [data-cor-cov]').textContent(), /166.667/);
      await page.locator('#cor-unit').selectOption('groups');
      assert.match(await page.locator('#cor-unit-result [data-cor-cov]').textContent(), /16.667/);
      assert.equal(await page.locator('#cor-unit-result [data-cor-rho]').textContent(), 'ρ = 1');
      await page.locator('#cor-unit').selectOption('cups');
      await page.locator('#cor-unit').selectOption('groups');
      assert.match(await page.locator('#cor-unit-result').textContent(), /1\/10/);
      assert.equal(await page.locator('#cor-units-answer').getAttribute('open'), null);
      await page.locator('#cor-units-answer summary').click();
      assert.match(await page.locator('#cor-units-answer').textContent(), /ρ = −1/);
      await page.locator('#cor-units-answer summary').click();
      assert.equal(await page.locator('#cor-units-answer').getAttribute('open'), null);
      await page.locator('#cor-unit').scrollIntoViewIfNeeded();
      await page.screenshot({path: `test-results/correlation-units-${viewport.width}.png`});
      assert.equal(await page.locator('#cor-asset-result [data-cor-vol]').textContent(), '2.449%');
      await page.locator('#cor-asset').selectOption('C');
      assert.equal(await page.locator('#cor-asset-result [data-cor-rho]').textContent(), 'ρ = -1');
      assert.equal(await page.locator('#cor-asset-result [data-cor-vol]').textContent(), '0.816%');
      await page.locator('#cor-asset').selectOption('B');
      await page.locator('#cor-asset').selectOption('C');
      assert.equal(await page.locator('#cor-volatility-answer').getAttribute('open'), null);
      await page.locator('#cor-volatility-answer summary').focus(); await page.keyboard.press('Enter');
      assert.equal(await page.locator('#cor-volatility-answer').getAttribute('open'), '');
      await page.keyboard.press('Enter');
      await page.locator('#cor-asset').scrollIntoViewIfNeeded();
      await page.screenshot({path: `test-results/correlation-volatility-${viewport.width}.png`});
      assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1), true, 'correlation page overflow');
      await page.locator('#theme-toggle').click();
      assert.equal(await page.locator('#cor-asset').inputValue(), 'C');
      assert.equal(await page.locator('#cor-asset-result [data-cor-vol]').textContent(), '0.816%');
      // Weight matching keeps state through theme changes and supports repeated and keyboard input.
      assert.equal(await page.locator('#cor-weight-a').inputValue(), '45');
      assert.equal(await page.locator('[data-cor-weight-vol]').textContent(), '0.8165%');
      await page.locator('#cor-weight-match').click();
      assert.equal(await page.locator('#cor-weight-a').inputValue(), '60');
      assert.equal(await page.locator('[data-cor-weight-vol]').textContent(), '0%');
      assert.equal(await page.locator('[data-cor-weighted-a]').textContent(), '1.0887%');
      assert.equal(await page.locator('[data-cor-weighted-c]').textContent(), '1.0887%');
      assert.match(await page.locator('#cor-weight-result').textContent(), /精确为 2\/3 与 1\/3/);
      await page.locator('#cor-weight-equal').click(); await page.locator('#cor-weight-match').click();
      await page.locator('#cor-weight-a').focus(); await page.keyboard.press('ArrowRight');
      assert.equal(await page.locator('#cor-weight-a').evaluate(el => { const s=getComputedStyle(el); return s.outlineStyle !== 'none' && parseFloat(s.outlineWidth)>0; }), true, 'keyboard focus must be visible');
      assert.equal(await page.locator('#cor-weight-a').inputValue(), '61');
      assert.notEqual(await page.locator('[data-cor-weight-vol]').textContent(), '0%');
      await page.keyboard.press('Home');
      assert.equal(await page.locator('#cor-weight-a').inputValue(), '0');
      assert.equal(await page.locator('[data-cor-weight-vol]').textContent(), '3.266%');
      await page.keyboard.press('End');
      assert.equal(await page.locator('#cor-weight-a').inputValue(), '90');
      assert.equal(await page.locator('[data-cor-weight-vol]').textContent(), '1.633%');
      await page.locator('#cor-weight-match').focus(); await page.keyboard.press('Enter');
      await page.locator('#theme-toggle').click();
      assert.equal(await page.locator('#cor-weight-a').inputValue(), '60');
      assert.equal(await page.locator('[data-cor-weight-vol]').textContent(), '0%');
      assert.equal(await page.locator('#cor-weights-answer').getAttribute('open'), null);
      await page.locator('#cor-weights-answer summary').focus(); await page.keyboard.press('Enter');
      assert.equal(await page.locator('#cor-weights-answer').getAttribute('open'), '');
      assert.match(await page.locator('#cor-weights-answer').textContent(), /A 90 元、C 30 元/);
      await page.keyboard.press('Enter');
      assert.equal(await page.locator('#cor-weights-answer').getAttribute('open'), null);
      await page.locator('#cor-weight-a').scrollIntoViewIfNeeded();
      await page.screenshot({path: `test-results/risk-weights-${viewport.width}.png`});
      assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1), true, 'weight page overflow');
      // Positive correlation is not a count of matching signs; retain comparison state through theme changes.
      await page.locator('#cor-positive-case').waitFor();
      assert.equal(await page.locator('#cor-positive-case').inputValue(), 'imperfect');
      assert.equal(await page.locator('[data-cor-positive-cov]').textContent(), '3');
      assert.equal(await page.locator('[data-cor-positive-rho]').textContent(), 'ρ = 0.6');
      assert.equal(await page.locator('[data-cor-positive-var]').textContent(), '4');
      assert.equal(await page.locator('[data-cor-positive-vol]').textContent(), '2%');
      assert.equal(await page.locator('#cor-positive-answer').getAttribute('open'), null);
      await page.locator('#cor-positive-answer summary').focus(); await page.keyboard.press('Enter');
      assert.equal(await page.locator('#cor-positive-answer').getAttribute('open'), '');
      assert.match(await page.locator('#cor-positive-answer').textContent(), /2.236%/);
      await page.keyboard.press('Enter');
      assert.equal(await page.locator('#cor-positive-answer').getAttribute('open'), null);
      await page.locator('#cor-positive-case').selectOption('synchronous');
      assert.equal(await page.locator('[data-cor-positive-rho]').textContent(), 'ρ = 1');
      assert.equal(await page.locator('[data-cor-positive-cov]').textContent(), '5');
      assert.equal(await page.locator('[data-cor-positive-var]').textContent(), '5');
      assert.equal(await page.locator('[data-cor-positive-vol]').textContent(), '2.236%');
      await page.locator('#cor-positive-case').selectOption('imperfect');
      await page.locator('#cor-positive-case').selectOption('synchronous');
      await page.locator('#theme-toggle').click();
      assert.equal(await page.locator('#cor-positive-case').inputValue(), 'synchronous');
      assert.equal(await page.locator('[data-cor-positive-vol]').textContent(), '2.236%');
      await page.locator('#cor-positive-case').focus();
      await page.keyboard.press('ArrowUp');
      assert.equal(await page.locator('#cor-positive-case').inputValue(), 'imperfect');
      assert.equal(await page.locator('[data-cor-positive-vol]').textContent(), '2%');
      await page.locator('#cor-positive-case').scrollIntoViewIfNeeded();
      await page.screenshot({path: `test-results/positive-correlation-${viewport.width}.png`});
      assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1), true, 'positive correlation page overflow');
      // Direct links are the public URLs shared for each section.
      await page.goto(`${base}/#/lesson/l04?section=correlation-units`);
      await page.locator('#cor-unit').waitFor();
      assert.equal(await page.locator('#cor-unit').inputValue(), 'cups');
      await page.goto(`${base}/#/lesson/l04?section=correlation-volatility`);
      await page.locator('#cor-asset').waitFor();
      assert.equal(await page.locator('#cor-asset').inputValue(), 'B');
      await page.goBack(); await page.locator('#cor-unit').waitFor();
      await page.goForward(); await page.locator('#cor-asset').waitFor();
      assert.equal(await page.locator('[data-correlation-demo="volatility"]').count(), 1);
      await page.goto(`${base}/#/lesson/l04?section=risk-matching-weights`);
      await page.locator('#cor-weight-a').waitFor();
      assert.equal(await page.locator('#cor-weight-a').inputValue(), '45');
      await page.locator('#cor-weight-match').click();
      assert.equal(await page.locator('[data-cor-weight-vol]').textContent(), '0%');
      await page.goBack(); await page.locator('#cor-asset').waitFor();
      await page.goForward(); await page.locator('#cor-weight-a').waitFor();
      assert.equal(await page.locator('[data-correlation-demo="weights"]').count(), 1);
      assert.equal(await page.locator('#cor-weight-a').inputValue(), '45');
      console.log(`PASS risk weights ${viewport.width}: image, 45/45 and 60/30, slider endpoints, keyboard, folded exercise, theme and route history`);
      console.log(`PASS correlation ${viewport.width}: images, exact teaching models, unit/asset switches, exercises, keyboard, theme, route history, no overflow`);
      await page.goto(`${base}/#/lesson/l04?section=positive-correlation-diversification`);
      await page.locator('#cor-positive-case').waitFor();
      assert.equal(await page.locator('#cor-positive-case').inputValue(), 'imperfect');
      await page.locator('#cor-positive-case').selectOption('synchronous');
      await page.goBack(); await page.locator('#cor-weight-a').waitFor();
      await page.goForward(); await page.locator('#cor-positive-case').waitFor();
      assert.equal(await page.locator('[data-correlation-demo="positive"]').count(), 1);
      assert.equal(await page.locator('#cor-positive-case').inputValue(), 'imperfect');
      console.log(`PASS positive correlation ${viewport.width}: image, covariance/formula comparison, repeated changes, keyboard, folded answer, theme and route history`);

      // Matrix lesson: four weighted cells, repeated controls, keyboard, theme, folded answer and direct link.
      await page.goto(`${base}/#/lesson/l04?section=covariance-matrix-four-cells`);
      await page.locator('#cor-matrix-weight').waitFor();
      const matrixImage=page.locator('img[src="assets/images/covariance-matrix-four-cells.png"]');
      await matrixImage.scrollIntoViewIfNeeded();
      await matrixImage.evaluate(async img => { if (!img.complete) await new Promise((resolve,reject)=>{img.onload=resolve;img.onerror=reject;}); if(img.naturalWidth!==1800)throw new Error('matrix image missing'); });
      assert.equal(await page.locator('#cor-matrix-weight').inputValue(),'50');
      for(const [cell,value] of Object.entries({aa:'1.25',ab:'0.75',ba:'0.75',bb:'1.25',var:'4',vol:'2%',check:'4'}))assert.equal(await page.locator(`[data-cor-matrix-${cell}]`).textContent(),value);
      assert.equal(await page.locator('#cor-matrix-answer').getAttribute('open'),null);
      await page.locator('#cor-matrix-answer summary').focus();await page.keyboard.press('Enter');
      assert.equal(await page.locator('#cor-matrix-answer').getAttribute('open'),'');
      assert.match(await page.locator('#cor-matrix-answer').textContent(),/2.062%/);
      await page.keyboard.press('Enter');
      assert.equal(await page.locator('#cor-matrix-answer').getAttribute('open'),null);
      await page.locator('#cor-matrix-three-one').click();
      for(const [cell,value] of Object.entries({aa:'2.8125',ab:'0.5625',ba:'0.5625',bb:'0.3125',var:'4.25',vol:'2.062%',check:'4.25'}))assert.equal(await page.locator(`[data-cor-matrix-${cell}]`).textContent(),value);
      await page.locator('#cor-matrix-equal').click();await page.locator('#cor-matrix-three-one').click();
      await page.locator('#theme-toggle').click();
      assert.equal(await page.locator('#cor-matrix-weight').inputValue(),'75');
      assert.equal(await page.locator('[data-cor-matrix-var]').textContent(),'4.25');
      await page.locator('#cor-matrix-weight').focus();await page.keyboard.press('Home');
      assert.equal(await page.locator('#cor-matrix-weight').inputValue(),'0');
      assert.equal(await page.locator('[data-cor-matrix-var]').textContent(),'5');
      await page.keyboard.press('End');assert.equal(await page.locator('#cor-matrix-weight').inputValue(),'100');
      assert.equal(await page.locator('[data-cor-matrix-var]').textContent(),'5');
      await page.keyboard.press('ArrowLeft');assert.equal(await page.locator('#cor-matrix-weight').inputValue(),'99');
      await page.locator('#cor-matrix-three-one').click();
      await page.locator('#cor-matrix-weight').scrollIntoViewIfNeeded();
      await page.screenshot({path:`test-results/matrix-four-cells-${viewport.width}.png`});
      assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1),true,'matrix page overflow');
      await page.goBack();await page.locator('#cor-positive-case').waitFor();
      await page.goForward();await page.locator('#cor-matrix-weight').waitFor();
      assert.equal(await page.locator('[data-correlation-demo="matrix"]').count(),1);
      assert.equal(await page.locator('#cor-matrix-weight').inputValue(),'50');
      console.log(`PASS matrix four cells ${viewport.width}: image, four terms, 50/50 and 75/25, endpoints, keyboard, repeated buttons, folded answer, theme, history, no overflow`);

      // Daily consolidation: both denominators, full image and default-folded answers.
      await page.goto(`${base}/#/lesson/l04?section=sample-covariance-denominator`);
      await page.locator('#sample-covariance-denominator').waitFor();
      const sampleSection = page.locator('[aria-labelledby="sample-covariance-denominator"]');
      const sampleImage = sampleSection.locator('img');
      await sampleImage.scrollIntoViewIfNeeded();
      await sampleImage.evaluate(img => img.decode());
      assert.deepEqual(await sampleImage.evaluate(img => [img.naturalWidth,img.naturalHeight]),[1600,1960]);
      assert.match(await sampleSection.textContent(), /2.309/);
      for (const id of ['sample-denominator-why','sample-denominator-answer']) {
        const detail=page.locator(`#${id}`);
        assert.equal(await detail.evaluate(el=>el.open),false);
        await detail.locator('summary').click();assert.equal(await detail.evaluate(el=>el.open),true);
        await detail.locator('summary').press('Enter');assert.equal(await detail.evaluate(el=>el.open),false);
        await detail.locator('summary').press('Enter');assert.equal(await detail.evaluate(el=>el.open),true);
        await detail.locator('summary').click();assert.equal(await detail.evaluate(el=>el.open),false);
      }
      assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);
      await page.locator('#sample-covariance-denominator').scrollIntoViewIfNeeded();
      await page.screenshot({path:`test-results/sample-denominator-${viewport.width}.png`});
      await page.locator('#theme-toggle').click();
      assert.equal(await sampleSection.isVisible(),true);
      await page.locator('#theme-toggle').click();
      console.log(`PASS sample denominator ${viewport.width}: direct section, 1600x1960 image, both disclosures, repeat click/keyboard, theme, no overflow`);

      await page.locator('#article-body a[href="#/lab/covariance"]').first().click();
      await page.locator('#cov-next').waitFor();
      await page.locator('#cov-next').click();
      assert.equal(await page.locator('#cov-step-count').textContent(), '2 / 5');
      await page.goBack();
      await page.locator('#article-body').waitFor();
      await page.goForward();
      await page.locator('#cov-next').waitFor();
      assert.equal(await page.locator('#cov-step-count').textContent(), '1 / 5');
      await page.locator('#cov-next').click();
      assert.equal(await page.locator('#cov-step-count').textContent(), '2 / 5');
      // Unrelated home, old lesson and existing lab still render.
      await page.goto(`${base}/#/home`); await page.locator('h1').waitFor();
      await page.goto(`${base}/#/lesson/l03`); await page.locator('#article-body').waitFor();
      await page.goto(`${base}/#/lab/portfolio`); await page.locator('canvas').first().waitFor();
      assert.deepEqual(errors, []);
      console.log(`PASS Chromium ${viewport.width}×${viewport.height}: all cases, 5 steps, basis, quiz retry/reset, keyboard, theme, Back/Forward, overflow and existing routes`);
      await page.close();
    }
  } finally { if (browser) await browser.close(); server.kill(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
